"""Weather API routes for MeshCenter."""

from __future__ import annotations

import os
import re
import tempfile

from flask import jsonify, request


_API_KEY_PATTERN = re.compile(r"^[A-Za-z0-9_-]{20,128}$")


def _normalize_api_key(value):
    key = str(value or "").strip()
    if not key:
        return ""
    if not _API_KEY_PATTERN.fullmatch(key):
        return ""
    return key


def _save_weather_secret(path, api_key):
    """Write the API key atomically and keep the secret file private."""
    path = os.path.abspath(path)
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)

    content = (
        '"""Local OpenWeather secret. Generated by MeshCenter.\n'
        "Do not commit this file to Git.\n"
        '"""\n\n'
        f'OPENWEATHER_API_KEY = "{api_key}"\n'
    )

    fd, temporary_path = tempfile.mkstemp(
        prefix=".weather_secrets.",
        suffix=".tmp",
        dir=directory,
        text=True,
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_path, 0o600)
        os.replace(temporary_path, path)
        os.chmod(path, 0o600)
    finally:
        if os.path.exists(temporary_path):
            os.unlink(temporary_path)


def register_weather_routes(
    app,
    weather_service,
    resolve_location=None,
    secrets_path=None,
):
    def resolved_location():
        location = resolve_location() if callable(resolve_location) else None
        return location if isinstance(location, dict) else {}

    @app.get("/api/weather/current")
    def api_weather_current():
        force = request.args.get("refresh", "").lower() in {"1", "true", "yes"}
        location = resolved_location()

        payload = weather_service.get_current(
            force=force,
            latitude=location.get("latitude"),
            longitude=location.get("longitude"),
            location_name=location.get("name", ""),
            location_source=location.get("source", "configured"),
        )
        return jsonify(payload), 200 if payload.get("ok") else 503

    @app.get("/api/weather/config")
    def api_weather_config_status():
        return jsonify({
            "ok": True,
            "configured": weather_service.is_configured(),
        })

    @app.post("/api/weather/config/test")
    def api_weather_test_key():
        data = request.get_json(silent=True) or {}
        api_key = _normalize_api_key(data.get("api_key"))
        if not api_key:
            return jsonify({
                "ok": False,
                "error": "Enter a valid OpenWeather API key.",
            }), 400

        location = resolved_location()
        result = weather_service.test_api_key(
            api_key,
            latitude=location.get("latitude"),
            longitude=location.get("longitude"),
        )
        return jsonify(result), 200 if result.get("ok") else 400

    @app.post("/api/weather/config")
    def api_weather_save_key():
        data = request.get_json(silent=True) or {}
        api_key = _normalize_api_key(data.get("api_key"))
        if not api_key:
            return jsonify({
                "ok": False,
                "error": "Enter a valid OpenWeather API key.",
            }), 400

        location = resolved_location()
        test_result = weather_service.test_api_key(
            api_key,
            latitude=location.get("latitude"),
            longitude=location.get("longitude"),
        )
        if not test_result.get("ok"):
            return jsonify(test_result), 400

        if not secrets_path:
            return jsonify({
                "ok": False,
                "error": "Weather secret storage is not configured.",
            }), 500

        try:
            _save_weather_secret(secrets_path, api_key)
            weather_service.set_api_key(api_key)
        except OSError as exc:
            return jsonify({
                "ok": False,
                "error": f"Could not save the OpenWeather API key: {exc}",
            }), 500

        return jsonify({
            "ok": True,
            "configured": True,
            "message": "OpenWeather API key saved successfully.",
        })
